version: '3.8'
services:
  calculator-api:
    build: .
    ports:
      - "3000:3000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/add?n1=1&n2=1"]
      interval: 30s
      timeout: 10s
      retries: 3